### ISSUE TITLE
Migrating to travis-ci.com to fix CI

### ISSUE THREAD

**Issue by v4hn** [ros-planning/moveit#1973] opened 2020-03-24 17:11 UTC
Why does Travis not run `moveit_ci` for pull-requests against `melodic-devel`?

https://github.com/ros-planning/moveit/pull/1971#issuecomment-603364181

@davetcoleman @henningkayser @rhaschke ... Forward as required.

**Comment by rhaschke** [comment] 2020-03-24 21:43
On our github repository somebody disabled all required checks, which I fixed meanwhile. However, Travis is not triggered for another reason, which I don't understand yet.
@davetcoleman, did you guys at Picknik changed the configuration recently?

**Comment by rhaschke** [comment] 2020-03-24 21:44
The moveit repo doesn't even show up on my Travis account!?!

**Comment by rhaschke** [comment] 2020-03-24 21:47
github oauth services seem to be deprecated and we should switch to github apps:
https://github.com/ros-planning/moveit/settings/installations

**Comment by rhaschke** [comment] 2020-03-25 18:59
Seems to work again (see #1975 and #1972), but I didn't explicitly change anything...

**Comment by davetcoleman** [comment] 2020-03-26 15:07
The moveit repo disappeared from my travis account also :-/

**Comment by gavanderhoorn** [comment] 2020-03-26 15:09
@rhaschke wrote:
> github oauth services seem to be deprecated and we should switch to github apps:
> https://github.com/ros-planning/moveit/settings/installations

I believe you are correct.

The non-app integration has been deprecated for quite some time now.

This needs to be fixed at the organisation level.

**Comment by rhaschke** [comment] 2020-03-26 15:47
Seems to be still an issue, e.g. in https://github.com/ros-planning/moveit/pull/1964.

**Comment by rhaschke** [comment] 2020-03-26 15:48
What is really strange, that it seemed to work for master, but not for melodic.

**Comment by davetcoleman** [comment] 2020-03-26 16:07
I'm setting up Travis CI as a Github App now

**Comment by rhaschke** [comment] 2020-03-27 14:13
The branch protection still uses the [old method](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154):
![image](https://user-images.githubusercontent.com/5376030/77764013-3a7f6e80-703c-11ea-9172-9404ba0b14fe.png)
But there is no other option!

Do we need to [migrate our repositories from travis-ci.org to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) [here](https://travis-ci.com/organizations/ros-planning/migrate)? There, it is stated that this is a beta feature.

@gavanderhoorn, can you provide a hint, please?

**Comment by gavanderhoorn** [comment] 2020-03-27 14:14
I don't recall whether migration is required, but it would not hurt, as `travis-ci.org` is going away, iirc.

**Comment by rhaschke** [comment] 2020-03-27 14:19
Can you verify whether you migrated, i.e. do travis links bring you to travis-ci.**org** or travis-ci.**com**? I puzzled, why we don't see the GitHub App checks in branch settings.

**Comment by gavanderhoorn** [comment] 2020-03-27 14:21
I have migrated everything. What I meant was that I don't remember whether migration is required to get the app to work.

> I puzzled, why we don't see the GitHub App checks in branch settings.

Afaik it only shows up when a build has been triggered at least once. And for that to happen, it needs to be configured correctly.

But again: I don't know whether this is what is causing the problems with CI here at `ros-planning/moveit`.

**Comment by davetcoleman** [comment] 2020-03-27 16:22
We're switched to an app rather than the depreciated service (for Travis, not Docker yet):

![image](https://user-images.githubusercontent.com/561060/77777095-a817a480-7014-11ea-8cf0-8c949b7eafdf.png)

I didn't know travis-ci.org is going away, does that mean the free accounts are going away also? PickNik currently pays for a .com business account for our internal projects, not sure if that is relevant or helpful.

**Comment by gavanderhoorn** [comment] 2020-03-27 16:23
Did you also configure the travis app and allow it access to the relevant repositories?

**Comment by rhaschke** [comment] 2020-03-27 17:02
Where do you configure it? Travis can see all the repositories and moveit is correctly configured I think:
![image](https://user-images.githubusercontent.com/5376030/77781018-25630980-7055-11ea-8532-e66fb82aab68.png)

**Comment by gavanderhoorn** [comment] 2020-03-27 17:07
Seems Travis has been having some trouble: [traviscistatus.com](https://www.traviscistatus.com/) (search for "March 26").

**Comment by gavanderhoorn** [comment] 2020-03-27 17:12
And that's a screenshot of `travis-ci.org`. I'm not an expert here, but if you go to https://github.com/organizations/ros-planning/settings/installations and click on *Configure* for `Travis CI` in that list, it should how you the list of repositories it's allowed to access.

Alternatively, go to `travis-ci.com`, login with your GH account and check the settings for `ros-planning/moveit` (or `ros-planning`, as it lists repositories by organisation).

**Comment by rhaschke** [comment] 2020-03-28 09:13
The MoveIt repos are definitely not yet migrated to travis-ci.com.
Looking at the mentioned [settings page](https://github.com/ros-planning/moveit/settings/installations), I cannot see a _Configure_ button. Obviously, I am missing permissions to configure those.
@davetcoleman, do you mind to grant me permissions for this as well:
https://github.com/organizations/ros-planning/settings/apps ?

**Comment by davetcoleman** [comment] 2020-06-02 14:25
Permission granted.

Can we close this issue? I assume we've figured out CI by now for the new approach?

**Comment by rhaschke** [comment] 2020-06-02 15:49
Sorry, @davetcoleman, but I still don't have permissions to configure github apps. Nothing changed yet, we are still running on the flaky (and deprecated) travis.org.

![image](https://user-images.githubusercontent.com/5376030/83541000-58b09180-a4f9-11ea-9767-388d9430ea76.png)

**Comment by davetcoleman** [comment] 2020-06-02 17:05
I did grant you the requested permission, but I'm not sure what else might be wrong:
![image](https://user-images.githubusercontent.com/561060/83548465-08b5d880-a4c1-11ea-83bf-b6d7bed52eea.png)

**Comment by rhaschke** [comment] 2020-06-02 17:37
No idea.

**Comment by davetcoleman** [comment] 2020-06-02 19:03
I'm reading through [Beta - Migrating repositories to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)

The issue is on this step:
> Select the repositories you’d like to migrate and click “Migrate selected repositories”, You’ll be asked for a final confirmation - please remember that you’ll need to update protected branches (See: Do I need to make any other changes?).

It says:
![image](https://user-images.githubusercontent.com/561060/83559192-62be9a00-a4d1-11ea-96a7-1bc9a8b2b22a.png)

Other TODOs:
- [ ] “Protected Branches” feature in GitHub to require a passing Travis CI build before merging a Pull Request: make sure to edit your required status checks to now use Travis CI - Pull Request and/or Travis CI - Branch. See: Required status checks at GitHub.

**Comment by v4hn** [comment] 2020-06-02 19:07
Let's wait for the response of Travis Support then. Thanks for looking into it @davetcoleman

**Comment by davetcoleman** [comment] 2020-06-02 19:10
Just emailed support.

**Comment by davetcoleman** [comment] 2020-06-02 22:39
I got a response, they fixed something, I completed the migration. Not sure if our CI still works, looking into that now...

**Comment by rhaschke** [comment] 2020-06-02 23:02
Looks like migration was successful: https://travis-ci.com/github/ros-planning

**Comment by davetcoleman** [comment] 2020-06-03 14:13
Going to close this!

**Closed by davetcoleman** 2020-06-03 14:13 UTC
Labels: bug, ci, melodic
