### ISSUE TITLE
could you please adapt voxel method to moveit  or speed up refresh octomap

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3413] opened 2023-04-28 06:23 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use octomap in moveit, it produce octomap too slow ,it limit us to use dynamic obstacle avoidance 
At present  in moveit  if a new point cloud appears, rviz can quickly see that the corresponding node in octomap is updated to the occupied state, but it can be seen in rviz that the originally occupied ocotmap is updated to free status after a long time after the point cloud leaves ,t is about 2 seconds dealy after the pointclouds move away  ,and I has commit an issue in the link  https://github.com/ros-planning/moveit/issues/3411
the number of pointcloud input moveit is about 660 which has been produced by downsample and the topic frequency is about 6 hz and the planning scene update frequncy is about 4~5hz.

and somebody else also found the problem ,you can see the web link
https://answers.ros.org/question/329125/octomap-gpu-voxel-franka-moveit-collision-avoidance-help/,he found that
The Octomaps refresh very slowly, at least in rviz. I would say about 2 Seconds when i put an obstacle into the view of the 3D cameras. I tried to limit the octomap distances, bigger voxels, etc. It is still very slow. When i display the two original point cloud topic streams from both the camera nodes, they display flawlessly with 60 fps. Is it still to much data for octomap?

**Describe the solution you'd like**
1)Could you please adapt voxel method to moveit  or speed up octomap refresh after point-cloud move away we hope that the occupied grid can be quickly updated to the free grid state

**Comment by rhaschke** [comment] 2023-04-28 07:05
You are welcome to file a PR to address those problems. The number of active maintainers for MoveIt1 dramatically decreased since most of us are focussing on ROS2 development now. As nobody replied to your original issue #3411 yet, I'm afraid there is nobody around to tackle your issue anytime soon. I suggest checking the update frequency of the octomap updater first.

Closing this issue as a duplicate of #3411.

**Closed by rhaschke** 2023-04-28 07:05 UTC
Labels: enhancement
