### ISSUE TITLE
Kinematics plugin fails to load

### ISSUE THREAD

**Issue by dav45** [ros-planning/moveit#1066] opened 2018-09-21 07:53 UTC
Hello! Newbie here. I am trying to do some motion planning for 7-DOF kinova jaco robot arm. The files were made using Ubuntu 14.04 with ROS Indigo but I need to load them on Ubuntu 16.04 for my application. I updated all the moveit Cmakelists.txt files by adding add_compile_options(-std=c++11) at the start of all of them and it allowed me to roslaunch the robot arm on Ubuntu 16.04 and view it but it wouldn't let me do any motion planning. I'm guessing it's because of the Kinematics plugin errors. Any help on how to go about fixing this issue would be much appreciated.

### My environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04

### Steps to reproduce
This is what I did:
1- Get the old moveit files to the catkin_ws/src folder from https://github.com/Kinovarobotics/kinova-ros/tree/master/kinova_moveit
2- Change all Cmakelists.txt files by adding add_compile_options(-std=c++11) line at he the beginning of all of them (there are only 6)
3- cd to catkin_ws and run catkin_make
4- Launch the moveit file with roslaunch j2n6s300_moveit_config j2n6s300_virtual_robot_demo.launch

### Expected behaviour
Moveit.RViz window should open and after loading the arm, there should be a set of axes or arrows at the virtual arm's hand to move it for motion planning.

### Actual behaviour
The moveit.RViz window opens and loads the arm but only after the terminal spits out a few errors. Then the arm cannot be moved at all after it's loaded, and there are no axes or arrows to move the virtual arm.

### Backtrace or Console output
<details>

```
nvidia@tegra-ubuntu:~/catkin_ws$ roslaunch j2n6s300_moveit_config j2n6s300_virtual_robot_demo.launch
... logging to /home/nvidia/.ros/log/33117506-bd6b-11e8-8667-00044ba51d7f/roslaunch-tegra-ubuntu-2596.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /home/nvidia/ws_moveit/src/kinova_description/urdf/j2n6s300_standalone.xacro

xacro.py is deprecated; please use xacro instead
started roslaunch server http://tegra-ubuntu:35132/

SUMMARY
========

PARAMETERS
 * /joint_state_publisher/use_gui: False
 * /joint_state_publisher/zeros/j2n6s300_joint_2: 3.1415
 * /joint_state_publisher/zeros/j2n6s300_joint_3: 3.1415
 * /move_group/allow_trajectory_execution: True
 * /move_group/allowed_execution_duration_scaling: 1.2
 * /move_group/allowed_goal_duration_margin: 0.5
 * /move_group/arm/planner_configs: ['SBLkConfigDefau...
 * /move_group/capabilities: move_group/MoveGr...
 * /move_group/controller_list: [{'joints': ['j2n...
 * /move_group/gripper/planner_configs: ['SBLkConfigDefau...
 * /move_group/initial: [{'pose': 'Home',...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_fake_contr...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/start_state_max_bounds_error: 0.1
 * /pick_place_demo/arm/solve_type: Manipulation2
 * /robot_connected: False
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/arm/kinematics_solver: trac_ik_kinematic...
 * /robot_description_kinematics/arm/kinematics_solver_attempts: 3
 * /robot_description_kinematics/arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/arm/kinematics_solver_timeout: 0.005
 * /robot_description_kinematics/arm/solve_type: Distance
 * /robot_description_planning/joint_limits/j2n6s300_joint_1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_1/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_1/max_velocity: 0.35
 * /robot_description_planning/joint_limits/j2n6s300_joint_2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_2/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_2/max_velocity: 0.35
 * /robot_description_planning/joint_limits/j2n6s300_joint_3/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_3/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_3/max_velocity: 0.35
 * /robot_description_planning/joint_limits/j2n6s300_joint_4/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_4/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_4/max_velocity: 0.35
 * /robot_description_planning/joint_limits/j2n6s300_joint_5/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_5/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_5/max_velocity: 0.35
 * /robot_description_planning/joint_limits/j2n6s300_joint_6/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_6/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_6/max_velocity: 0.35
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_1/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_1/max_velocity: 5
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_2/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_2/max_velocity: 5
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_3/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_3/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_3/max_velocity: 5
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_1/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_1/max_velocity: 5
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_2/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_2/max_velocity: 5
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_3/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_3/max_acceleration: 0
 * /robot_description_planning/joint_limits/j2n6s300_joint_finger_tip_3/max_velocity: 5
 * /robot_description_semantic: <?xml version="1....
 * /robot_type: j2n6s300
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rviz_tegra_ubuntu_2596_1144104855312537074/arm/kinematics_solver: trac_ik_kinematic...
 * /rviz_tegra_ubuntu_2596_1144104855312537074/arm/kinematics_solver_attempts: 3
 * /rviz_tegra_ubuntu_2596_1144104855312537074/arm/kinematics_solver_search_resolution: 0.005
 * /rviz_tegra_ubuntu_2596_1144104855312537074/arm/kinematics_solver_timeout: 0.005
 * /rviz_tegra_ubuntu_2596_1144104855312537074/arm/solve_type: Distance
 * /source_list: ['/move_group/fak...

NODES
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_tegra_ubuntu_2596_1144104855312537074 (rviz/rviz)

auto-starting new master
process[master]: started with pid [2616]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 33117506-bd6b-11e8-8667-00044ba51d7f
process[rosout-1]: started with pid [2630]
started core service [/rosout]
process[joint_state_publisher-2]: started with pid [2647]
process[robot_state_publisher-3]: started with pid [2648]
process[move_group-4]: started with pid [2649]
process[rviz_tegra_ubuntu_2596_1144104855312537074-5]: started with pid [2650]
[ INFO] [1537512878.944893954]: Loading robot model 'j2n6s300'...
[ WARN] [1537512878.945124726]: Skipping virtual joint 'world_joint' because its child frame 'root' does not match the URDF frame 'world'
[ INFO] [1537512878.945171867]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1537512879.115543095]: rviz version 1.12.16
[ INFO] [1537512879.115654208]: compiled against Qt version 5.5.1
[ INFO] [1537512879.115690179]: compiled against OGRE version 1.9.0 (Ghadamon)
[ERROR] [1537512879.575709921]: The kinematics plugin (arm) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin j2n6s300_arm_kinematics/IKFastKinematicsPlugin j2s7s300_robot_arm_kinematics/IKFastKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin m1n6s300_mico_arm_kinematics/IKFastKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
[ERROR] [1537512879.575853389]: Kinematics solver could not be instantiated for joint group arm.
[ INFO] [1537512880.144011908]: Stereo is NOT SUPPORTED
[ INFO] [1537512880.144226613]: OpenGl version: 4.5 (GLSL 4.5).
[ INFO] [1537512880.440994106]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1537512880.449661858]: MoveGroup debug mode is ON
Starting context monitors...
[ INFO] [1537512880.449768971]: Starting scene monitor
[ INFO] [1537512880.461591339]: Listening to '/planning_scene'
[ INFO] [1537512880.461681746]: Starting world geometry monitor
[ INFO] [1537512880.470792862]: Listening to '/collision_object' using message notifier with target frame '/world '
[ INFO] [1537512880.482786859]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1537512881.180975290]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1537512881.298567242]: Initializing OMPL interface using ROS parameters
[ INFO] [1537512881.380852435]: Using planning interface 'OMPL'
[ INFO] [1537512881.396150393]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1537512881.398558666]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1537512881.400813552]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1537512881.403505110]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1537512881.408582348]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1537512881.412360418]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1537512881.412622325]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1537512881.412700443]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1537512881.412759903]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1537512881.412814211]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1537512881.412856294]: Using planning request adapter 'Fix Start State Path Constraints'
[ WARN] [1537512881.419514193]: 
Deprecation warning: parameter 'allowed_execution_duration_scaling' moved into namespace 'trajectory_execution'.
Please, adjust file trajectory_execution.launch.xml!
[ WARN] [1537512881.421070179]: 
Deprecation warning: parameter 'allowed_goal_duration_margin' moved into namespace 'trajectory_execution'.
Please, adjust file trajectory_execution.launch.xml!
[ INFO] [1537512881.455241974]: Loading robot model 'j2n6s300'...
[ WARN] [1537512881.455344062]: Skipping virtual joint 'world_joint' because its child frame 'root' does not match the URDF frame 'world'
[ INFO] [1537512881.455410627]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ERROR] [1537512881.858710490]: The kinematics plugin (arm) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin j2n6s300_arm_kinematics/IKFastKinematicsPlugin j2s7s300_robot_arm_kinematics/IKFastKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin m1n6s300_mico_arm_kinematics/IKFastKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
[ERROR] [1537512881.858814721]: Kinematics solver could not be instantiated for joint group arm.
[ INFO] [1537512881.859101591]: Set joints of group 'arm' to pose 'Home'.
[ INFO] [1537512881.859994584]: Fake controller 'fake_arm_controller' with joints [ j2n6s300_joint_1 j2n6s300_joint_2 j2n6s300_joint_3 j2n6s300_joint_4 j2n6s300_joint_5 j2n6s300_joint_6 ]
[ INFO] [1537512881.861619920]: Fake controller 'fake_gripper_controller' with joints [ j2n6s300_joint_finger_1 j2n6s300_joint_finger_2 j2n6s300_joint_finger_3 ]
[ INFO] [1537512881.862893326]: Returned 2 controllers in list
[ INFO] [1537512881.898810466]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1537512882.142130253]: 

********************************************************
* MoveGroup using: 
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1537512882.142369214]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1537512882.142465157]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1537512884.021243738]: Loading robot model 'j2n6s300'...
[ WARN] [1537512884.021492265]: Skipping virtual joint 'world_joint' because its child frame 'root' does not match the URDF frame 'world'
[ INFO] [1537512884.021610480]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ERROR] [1537512884.512610244]: The kinematics plugin (arm) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin j2n6s300_arm_kinematics/IKFastKinematicsPlugin j2s7s300_robot_arm_kinematics/IKFastKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin m1n6s300_mico_arm_kinematics/IKFastKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
[ERROR] [1537512884.512939960]: Kinematics solver could not be instantiated for joint group arm.
[ INFO] [1537512885.402078677]: Starting scene monitor
[ INFO] [1537512885.413570019]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1537512886.063856056]: No active joints or end effectors found for group 'arm'. Make sure that kinematics.yaml is loaded in this node's namespace.
[ INFO] [1537512886.067600992]: Constructing new MoveGroup connection for group 'arm' in namespace ''
[ WARN] [1537512886.943056619]: 
Deprecation warning: Trajectory execution service is deprecated (was replaced by an action).
Replace 'MoveGroupExecuteService' with 'MoveGroupExecuteTrajectoryAction' in move_group.launch
[ INFO] [1537512886.952214387]: Ready to take commands for planning group arm.
[ INFO] [1537512886.952436191]: Looking around: no
[ INFO] [1537512886.952573798]: Replanning: no
```
</details>

The error I'm trying to understand and fix is:

```
[ERROR] [1537515270.389078750]: The kinematics plugin (arm) failed to load.
```

**Comment by gavanderhoorn** [comment] 2018-09-21 12:30
> ```
>[ERROR] [1537512884.512610244]: The kinematics plugin (arm) failed to load. Error: According to the loaded plugin descriptions the class trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin j2n6s300_arm_kinematics/IKFastKinematicsPlugin j2s7s300_robot_arm_kinematics/IKFastKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin m1n6s300_mico_arm_kinematics/IKFastKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
>[ERROR] [1537512884.512939960]: Kinematics solver could not be instantiated for joint group arm.
>```

According to this you don't have any of the kinova plugins configured for the `arm` group.

The problem is that the MoveIt config has specified the `trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin` as the IK solver for `arm` ([here](https://github.com/Kinovarobotics/kinova-ros/blob/949c8b22e54cbb108bb28cb3d14e99c299cb9c58/kinova_moveit/robot_configs/j2n6s300_moveit_config/config/kinematics.yaml#L2)), but you don't have it installed.

Make sure to have installed all dependencies for the packages that you are trying to use.

The `j2n6s300_moveit_config` package does not seem to list trac_ik as a dependency in its [package manifest](https://github.com/Kinovarobotics/kinova-ros/blob/949c8b22e54cbb108bb28cb3d14e99c299cb9c58/kinova_moveit/robot_configs/j2n6s300_moveit_config/package.xml). So you'll have to install it manually using `apt`.

The error has nothing to do with the ikfast plugins that Kinova provides.

**Comment by gavanderhoorn** [comment] 2018-09-21 12:31
As this does not appear to be an issue with MoveIt, I'm closing this.

If you still have issues and believe they are in the MoveIt packages, please re-open and clarify.

**Comment by gavanderhoorn** [comment] 2018-09-21 12:31
Also: could you please post questions regarding configuration issues on ROS Answers?

**Closed by gavanderhoorn** 2018-09-21 12:31 UTC

**Comment by dav45** [comment] 2018-09-21 20:26
@gavanderhoorn Thank you for the help! I will look into how to install all dependencies properly and will remember to post my questions regarding configuration issues on ROS Answers.
