### ISSUE TITLE
MoveIt! Perception Pipeline Tutorial fail to construct the octomap

### ISSUE THREAD

**Issue by lcmai** [ros-planning/moveit#1810] opened 2019-12-14 06:25 UTC
Hi, I am following the MoveIt! Perception Pipeline Tutorial and when I try to run 

`roslaunch moveit_tutorials obstacle_avoidance_demo.launch`

I only get the panda arm in the rviz and the console outputs are as follow:
~~~
SUMMARY
========

PARAMETERS
 * /joint_state_publisher/use_gui: False
 * /move_group/allow_trajectory_execution: True
 * /move_group/controller_list: [{'joints': ['pan...
 * /move_group/hand/planner_configs: ['SBLkConfigDefau...
 * /move_group/initial: [{'pose': 'ready'...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_fake_contr...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_frame: camera_rgb_optica...
 * /move_group/octomap_resolution: 0.05
 * /move_group/panda_arm/planner_configs: ['SBLkConfigDefau...
 * /move_group/panda_arm_hand/planner_configs: ['SBLkConfigDefau...
 * /move_group/planner_configs/BFMTkConfigDefault/balanced: 0
 * /move_group/planner_configs/BFMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/BFMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/BFMTkConfigDefault/heuristics: 1
 * /move_group/planner_configs/BFMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/BFMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/BFMTkConfigDefault/optimality: 1
 * /move_group/planner_configs/BFMTkConfigDefault/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMTkConfigDefault/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/BiESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiESTkConfigDefault/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRTkConfigDefault/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/init_temperature: 100
 * /move_group/planner_configs/BiTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/type: geometric::BiTRRT
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/FMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/FMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/FMTkConfigDefault/heuristics: 0
 * /move_group/planner_configs/FMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/FMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/FMTkConfigDefault/radius_multiplier: 1.1
 * /move_group/planner_configs/FMTkConfigDefault/type: geometric::FMT
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRTkConfigDefault/epsilon: 0.4
 * /move_group/planner_configs/LBTRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBTRRTkConfigDefault/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRMkConfigDefault/range: 0.0
 * /move_group/planner_configs/LazyPRMkConfigDefault/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstarkConfigDefault/type: geometric::LazyPR...
 * /move_group/planner_configs/PDSTkConfigDefault/type: geometric::PDST
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/ProjESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ProjESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ProjESTkConfigDefault/type: geometric::ProjEST
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/SPARSkConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARSkConfigDefault/max_failures: 1000
 * /move_group/planner_configs/SPARSkConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARSkConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARSkConfigDefault/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwokConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwokConfigDefault/max_failures: 5000
 * /move_group/planner_configs/SPARStwokConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwokConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwokConfigDefault/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDEkConfigDefault/degree: 16
 * /move_group/planner_configs/STRIDEkConfigDefault/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/STRIDEkConfigDefault/max_degree: 18
 * /move_group/planner_configs/STRIDEkConfigDefault/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDEkConfigDefault/min_degree: 12
 * /move_group/planner_configs/STRIDEkConfigDefault/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDEkConfigDefault/range: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDEkConfigDefault/use_projected_distance: 0
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planner_configs/TrajOptDefault/type: geometric::TrajOpt
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{'point_subsampl...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/allowed_start_tolerance: 0.01
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/panda_arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/panda_arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/panda_arm/kinematics_solver_timeout: 0.05
 * /robot_description_planning/joint_limits/panda_finger_joint1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/panda_finger_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_finger_joint1/max_acceleration: 0
 * /robot_description_planning/joint_limits/panda_finger_joint1/max_velocity: 0.1
 * /robot_description_planning/joint_limits/panda_finger_joint2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/panda_finger_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_finger_joint2/max_acceleration: 0
 * /robot_description_planning/joint_limits/panda_finger_joint2/max_velocity: 0.1
 * /robot_description_planning/joint_limits/panda_joint1/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint1/max_acceleration: 3.75
 * /robot_description_planning/joint_limits/panda_joint1/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint2/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint2/max_acceleration: 1.875
 * /robot_description_planning/joint_limits/panda_joint2/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint3/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint3/max_acceleration: 2.5
 * /robot_description_planning/joint_limits/panda_joint3/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint4/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint4/max_acceleration: 3.125
 * /robot_description_planning/joint_limits/panda_joint4/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint5/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint5/max_acceleration: 3.75
 * /robot_description_planning/joint_limits/panda_joint5/max_velocity: 2.61
 * /robot_description_planning/joint_limits/panda_joint6/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint6/max_acceleration: 5
 * /robot_description_planning/joint_limits/panda_joint6/max_velocity: 2.61
 * /robot_description_planning/joint_limits/panda_joint7/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint7/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint7/max_acceleration: 5
 * /robot_description_planning/joint_limits/panda_joint7/max_velocity: 2.61
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rviz_lcmai_XPS_15_9550_14106_2608243099174090805/panda_arm/kinematics_solver: kdl_kinematics_pl...
 * /rviz_lcmai_XPS_15_9550_14106_2608243099174090805/panda_arm/kinematics_solver_search_resolution: 0.005
 * /rviz_lcmai_XPS_15_9550_14106_2608243099174090805/panda_arm/kinematics_solver_timeout: 0.05
 * /source_list: ['/move_group/fak...

NODES
  /
    joint_state_desired_publisher (topic_tools/relay)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    point_clouds (moveit_tutorials/bag_publisher_maintain_time)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_lcmai_XPS_15_9550_14106_2608243099174090805 (rviz/rviz)
    to_panda_base (tf2_ros/static_transform_publisher)
    to_temp_link (tf2_ros/static_transform_publisher)
    virtual_joint_broadcaster_1 (tf2_ros/static_transform_publisher)

auto-starting new master
process[master]: started with pid [14125]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 6bf71e5c-1e36-11ea-94eb-48e244f642c1
process[rosout-1]: started with pid [14138]
started core service [/rosout]
process[virtual_joint_broadcaster_1-2]: started with pid [14155]
process[joint_state_publisher-3]: started with pid [14156]
process[joint_state_desired_publisher-4]: started with pid [14167]
process[robot_state_publisher-5]: started with pid [14168]
process[move_group-6]: started with pid [14179]
process[rviz_lcmai_XPS_15_9550_14106_2608243099174090805-7]: started with pid [14188]
process[point_clouds-8]: started with pid [14213]
process[to_temp_link-9]: started with pid [14214]
process[to_panda_base-10]: started with pid [14220]
[ INFO] [1576302969.327784658]: Loading robot model 'panda'...
[ INFO] [1576302969.408633105]: rviz version 1.12.17
[ INFO] [1576302969.408704237]: compiled against Qt version 5.5.1
[ INFO] [1576302969.408727903]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1576302969.447775652]: Loading robot model 'panda'...
[ INFO] [1576302969.491460504]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1576302969.495689208]: MoveGroup debug mode is ON
Starting context monitors...
[ INFO] [1576302969.495743797]: Starting scene monitor
[ INFO] [1576302969.499867004]: Listening to '/planning_scene'
[ INFO] [1576302969.499933381]: Starting world geometry monitor
[ INFO] [1576302969.505536664]: Listening to '/collision_object' using message notifier with target frame '/world '
[ INFO] [1576302969.510547959]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1576302969.537597680]: Listening to '/camera/depth_registered/points' using message filter with target frame '/world '
[ INFO] [1576302969.544106681]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ WARN] [1576302969.556368993]: Unable to update multi-DOF joint 'virtual_joint': TF has no common time between '/world' and 'panda_link0': Could not find a connection between 'world' and 'panda_link0' because they are not part of the same tree.Tf has two or more unconnected trees.
[ INFO] [1576302969.578478541]: Initializing OMPL interface using ROS parameters
[ INFO] [1576302969.626495921]: Using planning interface 'OMPL'
[ INFO] [1576302969.629449436]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1576302969.629949732]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1576302969.630405534]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1576302969.630867272]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1576302969.631292224]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1576302969.631733503]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1576302969.631776702]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1576302969.631795609]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1576302969.631811657]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1576302969.631829264]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1576302969.631846363]: Using planning request adapter 'Fix Start State Path Constraints'
[ INFO] [1576302969.641342999]: Loading robot model 'panda'...
[ INFO] [1576302969.717649697]: Loading robot model 'panda'...
[ INFO] [1576302969.726527585]: Set joints of group 'panda_arm_hand' to pose 'ready'.
[ INFO] [1576302969.726896522]: Fake controller 'fake_panda_arm_controller' with joints [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
[ INFO] [1576302969.727417722]: Fake controller 'fake_hand_controller' with joints [ panda_finger_joint1 panda_finger_joint2 ]
[ INFO] [1576302969.727894041]: Returned 2 controllers in list
[ INFO] [1576302969.742181243]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1576302969.812331752]: 

********************************************************
* MoveGroup using: 
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1576302969.812390559]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1576302969.812405815]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1576302969.907185968]: Stereo is NOT SUPPORTED
[ INFO] [1576302969.907303384]: OpenGl version: 3 (GLSL 1.3).
0x1299340 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x6f0880) ): Attempt to set a screen on a child window.
0x128f320 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x6f0880) ): Attempt to set a screen on a child window.
0x128fbb0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x6f0880) ): Attempt to set a screen on a child window.
0x1295a70 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x6f0880) ): Attempt to set a screen on a child window.
[ INFO] [1576302970.259530224]: Loading robot model 'panda'...
[ INFO] [1576302970.803439222]: Loading robot model 'panda'...
[ INFO] [1576302970.879332389]: Loading robot model 'panda'...
[ INFO] [1576302970.951475491]: Starting scene monitor
[ INFO] [1576302970.956275741]: Listening to '/move_group/monitored_planning_scene'
[ WARN] [1576302970.958025661]: No transform available between frame 'temp_link' and planning frame '/world' (Could not find a connection between 'world' and 'temp_link' because they are not part of the same tree.Tf has two or more unconnected trees.)
[ WARN] [1576302970.958064864]: No transform available between frame 'camera_rgb_optical_frame' and planning frame '/world' (Could not find a connection between 'world' and 'camera_rgb_optical_frame' because they are not part of the same tree.Tf has two or more unconnected trees.)
[ WARN] [1576303019.327252677]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1576303079.327679865]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1576303139.327909282]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1576303199.328182748]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1576303259.338625536]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1576303319.348346248]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
[ WARN] [1576303379.348482839]: MessageFilter [target=/world ]: Dropped 100.00% of messages so far. Please turn the [ros.moveit_ros_perception.message_notifier] rosconsole logger to DEBUG for more information.
~~~

**Comment by askkvn** [comment] 2020-04-28 06:28
Duplicate of #1220

**Comment by rhaschke** [comment] 2020-04-28 08:15
@mlautman, can you have a look at this in #1220, please?

**Closed by rhaschke** 2020-04-28 08:15 UTC
