### ISSUE TITLE
Errors when build moveit from souce

### ISSUE THREAD

**Issue by ranjitkathiriya** [ros-planning/moveit#2513] opened 2021-02-10 10:55 UTC
### Description

Hey there,

I am not able to build moveit package from the source, and while retrying I keep getting errors.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source

### Steps to reproduce
I followed this tutorial: http://moveit.ros.org/install/source/
I have also followed this tutorial: https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html

Both are throwing the same error.

### Expected behaviour
Build success!

### Actual behaviour
Getting this Errors of CURL_OPENSSL_4.

### Backtrace or Console output

```
(ros1_envs) kuka-ai@kukaai-ROG-Zephyrus-G15-GA502IU-GA502IU:~/ws_moveit$ catkin build
------------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/noetic
Workspace:                   /home/kuka-ai/ws_moveit
------------------------------------------------------------
Build Space:        [exists] /home/kuka-ai/ws_moveit/build
Devel Space:        [exists] /home/kuka-ai/ws_moveit/devel
Install Space:      [unused] /home/kuka-ai/ws_moveit/install
Log Space:          [exists] /home/kuka-ai/ws_moveit/logs
Source Space:       [exists] /home/kuka-ai/ws_moveit/src
DESTDIR:            [unused] None
------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
------------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
------------------------------------------------------------
Workspace configuration appears valid.
------------------------------------------------------------
[build] Found '45' packages in 0.0 seconds.                                    
[build] Package table is up to date.                                           
Starting  >>> geometric_shapes                                                 
Starting  >>> moveit_msgs                                                      
Starting  >>> moveit_resources_fanuc_description                               
Starting  >>> moveit_resources_panda_description                               
Starting  >>> moveit_resources_pr2_description                                 
Starting  >>> rviz_visual_tools                                                
Finished  <<< geometric_shapes                                               [ 0.5 seconds ]
Finished  <<< moveit_resources_pr2_description                               [ 0.5 seconds ]
Finished  <<< moveit_resources_fanuc_description                             [ 0.5 seconds ]
Finished  <<< moveit_resources_panda_description                             [ 0.3 seconds ]
Starting  >>> moveit_resources_fanuc_moveit_config                             
Starting  >>> moveit_resources_panda_moveit_config                             
Finished  <<< moveit_msgs                                                    [ 2.2 seconds ]
Finished  <<< rviz_visual_tools                                              [ 1.0 seconds ]
Finished  <<< moveit_resources_fanuc_moveit_config                           [ 0.2 seconds ]
Finished  <<< moveit_resources_panda_moveit_config                           [ 0.2 seconds ]
Starting  >>> moveit_resources                                                 
Starting  >>> moveit_core                                                      
Finished  <<< moveit_resources                                               [ 0.2 seconds ]
Finished  <<< moveit_core                                                    [ 0.9 seconds ]
Starting  >>> chomp_motion_planner                                             
Starting  >>> moveit_resources_prbt_ikfast_manipulator_plugin                  
Starting  >>> moveit_ros_occupancy_map_monitor                                 
Starting  >>> moveit_simple_controller_manager                                 
Finished  <<< chomp_motion_planner                                           [ 0.3 seconds ]
Starting  >>> moveit_chomp_optimizer_adapter                                   
Finished  <<< moveit_simple_controller_manager                               [ 0.2 seconds ]
Starting  >>> moveit_ros_control_interface                                     
Finished  <<< moveit_ros_occupancy_map_monitor                               [ 0.3 seconds ]
Starting  >>> moveit_ros_perception                                            
Starting  >>> moveit_ros_planning                                              
Finished  <<< moveit_resources_prbt_ikfast_manipulator_plugin                [ 0.2 seconds ]
Finished  <<< moveit_chomp_optimizer_adapter                                 [ 0.3 seconds ]
Finished  <<< moveit_ros_control_interface                                   [ 0.2 seconds ]
Finished  <<< moveit_ros_planning                                            [ 0.6 seconds ]
Starting  >>> moveit_fake_controller_manager                                   
Starting  >>> moveit_kinematics                                                
Starting  >>> moveit_planners_ompl                                             
Starting  >>> moveit_resources_prbt_support                                    
Starting  >>> moveit_ros_robot_interaction                                     
Starting  >>> moveit_ros_warehouse                                             
Starting  >>> moveit_visual_tools                                              
Finished  <<< moveit_ros_perception                                          [ 0.6 seconds ]
Finished  <<< moveit_ros_warehouse                                           [ 0.3 seconds ]
Starting  >>> moveit_ros_benchmarks                                            
Finished  <<< moveit_visual_tools                                            [ 0.3 seconds ]
Finished  <<< moveit_fake_controller_manager                                 [ 0.3 seconds ]
Starting  >>> moveit_plugins                                                   
Finished  <<< moveit_resources_prbt_support                                  [ 0.2 seconds ]
Starting  >>> moveit_resources_prbt_moveit_config                              
Finished  <<< moveit_ros_robot_interaction                                   [ 0.2 seconds ]
Finished  <<< moveit_planners_ompl                                           [ 0.4 seconds ]
Finished  <<< moveit_kinematics                                              [ 0.3 seconds ]
Starting  >>> moveit_ros_move_group                                            
Finished  <<< moveit_ros_benchmarks                                          [ 0.3 seconds ]
Finished  <<< moveit_plugins                                                 [ 0.2 seconds ]
Finished  <<< moveit_resources_prbt_moveit_config                            [ 0.2 seconds ]
Starting  >>> moveit_resources_prbt_pg70_support                               
Finished  <<< moveit_resources_prbt_pg70_support                             [ 0.2 seconds ]
Finished  <<< moveit_ros_move_group                                          [ 0.6 seconds ]
Starting  >>> moveit_ros_manipulation                                          
Finished  <<< moveit_ros_manipulation                                        [ 0.3 seconds ]
Starting  >>> moveit_ros_planning_interface                                    
_______________________________________________________________________________
Errors     << moveit_ros_planning_interface:make /home/kuka-ai/ws_moveit/logs/moveit_ros_planning_interface/build.make.002.log
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /lib/x86_64-linux-gnu/libapr-1.so.0: undefined reference to `uuid_generate@UUID_1.0'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/test_cleanup.dir/build.make:185: /home/kuka-ai/ws_moveit/devel/.private/moveit_ros_planning_interface/lib/moveit_ros_planning_interface/test_cleanup] Error 1
make[1]: *** [CMakeFiles/Makefile2:4261: test/CMakeFiles/test_cleanup.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_global_cleanup@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_global_init@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_perform@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_init@CURL_OPENSSL_4'
/usr/bin/ld: /lib/x86_64-linux-gnu/libapr-1.so.0: undefined reference to `uuid_generate@UUID_1.0'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_setopt@CURL_OPENSSL_4'
/usr/bin/ld: /opt/ros/noetic/lib/libresource_retriever.so: undefined reference to `curl_easy_cleanup@CURL_OPENSSL_4'
collect2: error: ld returned 1 exit status
make[2]: *** [move_group_interface/CMakeFiles/demo.dir/build.make:282: /home/kuka-ai/ws_moveit/devel/.private/moveit_ros_planning_interface/lib/moveit_ros_planning_interface/demo] Error 1
make[1]: *** [CMakeFiles/Makefile2:3321: move_group_interface/CMakeFiles/demo.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/kuka-ai/ws_moveit/build/moveit_ros_planning_interface; catkin build --get-env moveit_ros_planning_interface | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -
...............................................................................
Failed     << moveit_ros_planning_interface:make                             [ Exited with code 2 ]
Failed    <<< moveit_ros_planning_interface                                  [ 1.1 seconds ]
Abandoned <<< moveit                                                         [ Unrelated job failed ]
Abandoned <<< moveit_planners                                                [ Unrelated job failed ]
Abandoned <<< moveit_commander                                               [ Unrelated job failed ]
Abandoned <<< moveit_ros                                                     [ Unrelated job failed ]
Abandoned <<< moveit_planners_chomp                                          [ Unrelated job failed ]
Abandoned <<< moveit_ros_visualization                                       [ Unrelated job failed ]
Abandoned <<< moveit_runtime                                                 [ Unrelated job failed ]
Abandoned <<< moveit_servo                                                   [ Unrelated job failed ]
Abandoned <<< moveit_setup_assistant                                         [ Unrelated job failed ]
Abandoned <<< panda_moveit_config                                            [ Unrelated job failed ]
Abandoned <<< pilz_industrial_motion_planner_testutils                       [ Unrelated job failed ]
Abandoned <<< pilz_industrial_motion_planner                                 [ Unrelated job failed ]
Abandoned <<< moveit_tutorials                                               [ Unrelated job failed ]
[build] Summary: 31 of 45 packages succeeded.                                  
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: 13 packages were abandoned.                               
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 8.2 seconds total.  
```

**Comment by rhaschke** [comment] 2021-02-10 11:38
This seems to be a duplicate of https://github.com/ros-planning/moveit/issues/697. The reason is that you have a non-standard version of curl in your system. Please see comments in #697.

**Closed by rhaschke** 2021-02-10 11:38 UTC
Labels: bug

**Comment by ranjitkathiriya** [comment] 2021-02-10 11:40
Thanks!
