### ISSUE TITLE
include/moveit/mesh_filter missing on Kinetic

### ISSUE THREAD

**Issue by cc143** [ros-planning/moveit#953] opened 2018-06-19 14:25 UTC
### Description

Since installing the latest `.deb` from the ROS Kinetic apt repository, `/opt/ros/kinetic/include/moveit/mesh_filter` has disappeared.

### Your environment
* ROS Distro: Kinetic
* OS Version: Ubuntu 16.04
* Source or Binary build? Binary
* If binary, which release version? 0.9.12-1xenial-20180530-071129-0800

### Steps to reproduce
`apt update && apt upgrade`

The latest `.deb` does not appear to contain the `include/moveit/mesh_filter` directory or its contents, e.g. `mesh_filter.h`.

### Expected behaviour
Header files should not disappear when upgrading from one Kinetic release to another Kinetic release.

### Actual behaviour
The whole `moveit/mesh_filter` include directory and all its contents have vanished.

### Backtrace or Console output

```
$ ls -l /opt/ros/kinetic/include/moveit/mesh_filter
total 72
-rw-r--r-- 1 root root  5374 Dec 25 17:55 depth_self_filter_nodelet.h
-rw-r--r-- 1 root root  3781 Dec 25 17:55 filter_job.h
-rw-r--r-- 1 root root  3036 Dec 25 17:55 gl_mesh.h
-rw-r--r-- 1 root root 10772 Dec 25 17:55 gl_renderer.h
-rw-r--r-- 1 root root 11043 Dec 25 17:55 mesh_filter_base.h
-rw-r--r-- 1 root root  4352 Dec 25 17:55 mesh_filter.h
-rw-r--r-- 1 root root  6002 Dec 25 17:55 sensor_model.h
-rw-r--r-- 1 root root  6487 Dec 25 17:55 stereo_camera_model.h
-rw-r--r-- 1 root root  5758 Dec 25 17:55 transform_provider.h
$ apt update && apt upgrade
$ ls -l /opt/ros/kinetic/include/moveit/mesh_filter
ls: cannot access '/opt/ros/kinetic/include/moveit/mesh_filter': No such file or directory
```

**Comment by davetcoleman** [comment] 2018-06-19 23:57
Thank you for this detailed bug report! Seems similar to https://github.com/ros-planning/moveit/issues/943

**Comment by cc143** [comment] 2018-06-20 12:48
The ROS apt repository (i.e. `http://packages.ros.org/ros/ubuntu`) only appears to contain the latest version of each `.deb`. I would like to revert to a working version until this is fixed. Is that possible?

**Comment by rhaschke** [comment] 2018-10-21 20:18
Closing this as duplicate of #943.

**Closed by rhaschke** 2018-10-21 20:18 UTC
