### ISSUE TITLE
Moveit Setup Assistant can't parse XML description files

### ISSUE THREAD

**Issue by shreyasgan** [ros-planning/moveit#1036] opened 2018-08-24 19:00 UTC
### Description

[rospack] Error: no package given
[librospack]: error while executing command
[ INFO] [1535132859.993706205] Running 'rosrun xacro xacro.py --inorder /home/bashir/ws_moveit/src/staubli_experimental/staubli_tx90_support/urdf/tx90.xacro

XML parsing error: not well-formed (invalid token): line 27, column 1
when processing file:

Check that:
- Your XML is well-formed
- You have the xacro xmlns declaration: xmlns:xacro= "http://www.ros.org/wiki/xacro"

### Your environment
* ROS Distro: Indigo
* OS Version: e.g. Ubuntu 14.04
* Binary Build

### Steps to reproduce
clone the staubli_experimental package from github: https://github.com/ros-industrial/staubli_experimental
Then run setup assistant and try to open tx90.xacro

### Expected behaviour
Display a model of the TX90 in the setup assistant

### Actual behaviour
I recieve an error

**Comment by rhaschke** [comment] 2018-08-26 22:16
Works perfectly on my side. Did you checked the xacro command on the command line too?

**Comment by saurabhbansal90** [comment] 2018-08-30 18:39
Please try with upgraded MoveIt!

**Comment by BryceStevenWilley** [comment] 2019-06-20 03:51
Cannot reproduce, closing for now.

**Closed by BryceStevenWilley** 2019-06-20 03:51 UTC
