### ISSUE TITLE
how can we use moveit to remove robot arm from the pointcloud generated by 3d camera mounted outside the arm when build octomap 

### ISSUE THREAD

**Issue by dbdxnuliba** [ros-planning/moveit#3226] opened 2022-09-28 03:29 UTC
how can we use moveit to remove robot arm from the pointcloud generated by 3d camera mounted outside the arm when build octomap

**Comment by rhaschke** [comment] 2022-09-28 15:11
Duplicate of #3225

**Closed by rhaschke** 2022-09-28 15:11 UTC
Labels: bug
