### ISSUE TITLE
RobotState RVIz plugin only shows current state after de-/activating the plugin

### ISSUE THREAD

**Issue by christian-rauch** [ros-planning/moveit#1279] opened 2018-12-17 12:25 UTC
### Description

The RobotState RVIz plugin does not show the state of the robot in the published `moveit_msgs::DisplayRobotState`  message, if RViz is started with the plugin enables. The plugin only shows the state if it gets enabled via the tick-box.

### Your environment
* ROS Distro: melodic
* OS Version: Ubuntu 18.04
* Source or Binary build? Binary, 0.10.5

### Steps to reproduce
1. Publish `moveit_msgs::DisplayRobotState` messages on the default topic `display_robot_state`
2. Add the RobotState RVIz plugin to a RViz session and activate it
3. Observe that the visualised robot state changes
4. Save and close the RViz session
5. Start RViz with the same session (e.g. `rviz -d robot_state.rviz`)
6. The robot is shown in the zero configuration
7. Deactivate and activate the plugin again (untick/tick)
8. Observe that the robot is now shown in the published configuration

### Expected behaviour
At step 6., (starting RViz with activated RobotState plugin) the robot should already be shown in the published configuration.

### Actual behaviour
After starting RViz with enables RobotState plugin, the robot is shown in its zero configuration

### Demonstration
This video shows the issue. The robot only shows the published state, after disabling and re-enabling the RViz plugin.

![rviz_robot_state_bug](https://user-images.githubusercontent.com/8226248/50086926-823b0780-01f6-11e9-820e-bee0cd9180fa.gif)

**Comment by rhaschke** [comment] 2018-12-19 13:59
I cannot reproduce this issue: On my side, after restarting rviz, the robot is first shown in zero-pose shortly, but the next frame update immediately shows it in the published pose.
What confuses me about your video, is that the robot is shown in several poses in sequence. Why? Who publishes all these poses?

**Comment by christian-rauch** [comment] 2018-12-20 15:21
I am generating random robot configurations. It's basically a stream of `moveit_msgs::DisplayRobotState` messages.
I can reproduce the issue with this bag file [robot_states.bag.txt](https://github.com/ros-planning/moveit/files/2699348/robot_states.bag.txt) and this robot URDF [robot.urdf.txt](https://github.com/ros-planning/moveit/files/2699354/robot.urdf.txt) (full robot rescription is available at https://github.com/ipab-slmc/kuka_lwr4_description).

**Comment by rhaschke** [comment] 2018-12-24 07:59
Sorry, but even using a non-standard topic name, I cannot reproduce this issue. Maybe this was fixed in #1199? Could you validate this against MoveIt 0.10.7 please?

**Comment by christian-rauch** [comment] 2019-01-07 15:33
I get the same issue with `ros-melodic-moveit-ros-visualization` version 0.10.8.

This is the RViz configuration file that I am using (together with the before mentioned bag file):
[robot_state.rviz.txt](https://github.com/ros-planning/moveit/files/2733268/robot_state.rviz.txt). Line 194 (`Robot State Topic`) shows the default topic name `display_robot_state`.
If I play the bag file and open the RViz configuration file, the robot model does not change its state. Only after I prepend `/` to the default topic name and reopen the same configuration, the robot state changes according to the recorded messages in the bag file.

**Comment by rhaschke** [comment] 2019-01-16 14:48
Sorry, but I still cannot reproduce your issue. The referenced kuka description is incomplete (missing schunk_description, robotiq, ...). So I started to setup a simple example myself:
```
roslaunch moveit_resources demo.launch   # start up the fanuc arm
python robot_state.py  # publish random display states
rviz
```
You can easily modify the [robot_state.py script](https://github.com/ros-planning/moveit/files/2764578/robot_state.py.txt) to use your robot by changing the name of the move group. Any combination of starting rviz and the script immediately yields visible updates.

**Comment by rhaschke** [comment] 2019-08-17 10:43
Closing this as there was no more feedback since Jan. Please feel free to re-open if this is still an issue.

**Closed by rhaschke** 2019-08-17 10:43 UTC
