### ISSUE TITLE
Regressions on Jade

### ISSUE THREAD

**Issue by wjwwood** [ros-planning/moveit#39] opened 2016-08-11 18:49 UTC
I'd like to sync Jade, but moveit has regressions. It looks like Trusty has a regression for `moveit_ros_warehouse`:

http://build.ros.org/view/Jbin_uT64/job/Jbin_uT64__moveit_ros_warehouse__ubuntu_trusty_amd64__binary/72/console

**Comment by wjwwood** [comment] 2016-08-11 18:51
Sorry, accidentally hit `<tab>` then `<space>`...

---

I'd like to sync Jade, but moveit has regressions. It looks like Trusty has a regression for moveit_ros_warehouse:

http://build.ros.org/view/Jbin_uT64/job/Jbin_uT64__moveit_ros_warehouse__ubuntu_trusty_amd64__binary/72/console

If someone could look into that, I'd appreciate it. I think all of the moveit related regressions stem from this failure, but there may be others.

**Comment by v4hn** [comment] 2016-08-11 19:15
The problematic code has more or less recently been replaced by a plugin mechanism after long discussion:
https://github.com/ros-planning/moveit_ros/pull/699
A release is more or less on its way: https://github.com/ros-planning/moveit/issues/22

@130s, Sorry for the ping.. What's the state of this? We should probably aim to increase our bus-factor for releases.

**Comment by 130s** [comment] 2016-08-11 19:42
Yeah, as I [left a comment](https://github.com/ros-planning/moveit/issues/22#issuecomment-239268837), once we make a new release of `moveit` (that contains the current `moveit_ros`), this particular regression should be fixed.

**Comment by davetcoleman** [comment] 2016-08-11 20:09
I think we should move fast on releasing I/J so we don't hinder the sync

**Comment by davetcoleman** [comment] 2016-08-11 20:10
Side note: there's a pretty table of our Jade regressions in our README now: https://github.com/ros-planning/moveit

**Comment by v4hn** [comment] 2016-08-22 14:05
Fixed. See https://github.com/ros-planning/moveit/issues/22

**Closed by v4hn** 2016-08-22 14:05 UTC

**Comment by 130s** [comment] 2016-08-23 06:47
Jade DEBs are built and available from [shadow](http://wiki.ros.org/ShadowRepository) repository. 

Now Jade regression is almost gone http://repositories.ros.org/status_page/ros_jade_default.html?q=REGRESSION.

**Comment by davetcoleman** [comment] 2016-08-23 06:49
what is not gone yet? ompl?

**Comment by 130s** [comment] 2016-08-23 17:31
It is `ompl` for the entire Jade world for today. 
[I poked them](https://bitbucket.org/ompl/ompl/issues/266/ros-jade-new-version-is-older-than-the-one). Doesn't seem to be critical.

@wjwwood Sorry it took forever to get MoveIt! out for Jade. I assume we want some soak time (a week? 2 weeks? Anyone?) because the new release introduces the tremendous amount of changes.

**Comment by wjwwood** [comment] 2016-08-23 19:26
It would be prudent to have some time for people to test the new moveit in Jade. We can plan to do a sync in a week or so.

The ompl thing isn't a regression. It is them fixing their version numbers. They may need to make sure that future releases can be considered newer than what's already there. Since nothing has changed between the two numbers, that I'm aware of, it should be fine for now.

**Comment by davetcoleman** [comment] 2016-08-23 20:31
we've never officially released jade because it only worked on one platform, so i don't think we need much soak time

**Comment by wjwwood** [comment] 2016-08-23 21:07
That's also ok for me, since we've waited quite a while for Jade to sync already.
