### ISSUE TITLE
Group 'panda_manipulator' is empty & Link 'panda_hand_tcp' declared as part of a chain in group 'panda_manipulator' is not known to the URDF #141

### ISSUE THREAD

**Issue by upc-ghy** [ros-planning/moveit#3585] opened 2024-04-06 13:15 UTC
PC
Ubuntu 20.04
ros noetic
I have correctly installed libFranka and Franka'ros according to the tutorial before installing Moveit.
When I follow https://moveit.ros.org/install/source/ When installing Moveit 1.0 without errors in the tutorial, I conducted the following tests on the installed Moveit:

`﻿roslaunch panda_moveit_config franka_control.launch robot_ip:=172.16.3.69`

The following error was discovered as a result. My panda_arm are normal and can be planned and executed. Please give me some guidance, I would greatly appreciate it.
﻿
```

[ERROR] [1712405836.033605977]: Link 'panda_hand_tcp' declared as part of a chain in group 'panda_manipulator' is not known to the URDF
[ WARN] [1712405836.034432842]: Group 'panda_manipulator' is empty.
[ERROR] [1712405836.034619938]: Link 'panda_hand_tcp' specified as parent for end effector 'panda_hand_tcp' is not known to the URDF
[ WARN] [1712405836.034677136]: Link 'panda_link0_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034700140]: Link 'panda_link1_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034717929]: Link 'panda_link2_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034731492]: Link 'panda_link3_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034768325]: Link 'panda_link4_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034793043]: Link 'panda_link5_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034807518]: Link 'panda_link6_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034820876]: Link 'panda_link7_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034836366]: Link 'panda_hand_sc' is not known to URDF. Cannot specify collision default.
[ WARN] [1712405836.034854718]: Link 'panda_link0_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034872344]: Link 'panda_link0_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034888850]: Link 'panda_link0_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034906201]: Link 'panda_link1_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034921988]: Link 'panda_link1_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034956680]: Link 'panda_link1_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034975680]: Link 'panda_link2_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.034991159]: Link 'panda_link2_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.035023342]: Link 'panda_link2_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.035041088]: Link 'panda_link3_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.035059384]: Link 'panda_hand_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.035076916]: Link 'panda_hand_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.035092825]: Link 'panda_hand_sc' is not known to URDF. Cannot disable/enable collisons.
[ WARN] [1712405836.035108452]: Link 'panda_hand_sc' is not known to URDF. Cannot disable/enable collisons.
[ INFO] [1712405836.035351175]: Loading robot model 'panda'...
[ WARN] [1712405836.035575992]: Link panda_leftfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1712405836.035610516]: Link panda_rightfinger has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[ WARN] [1712405836.035784795]: Group 'panda_manipulator' must have at least one valid joint
[ WARN] [1712405836.035829821]: Failed to add group 'panda_manipulator'
[ERROR] [1712405836.035934909]: Group state 'ready' specified for group 'panda_manipulator', but that group does not exist
[ERROR] [1712405836.035955326]: Group state 'extended' specified for group 'panda_manipulator', but that group does not exist
```

**And as long as I run 
roslauch franka_control franka_control. launch robot_ip:=172.16.3.69 load_gripper:=true,
it will change from ready to end effector unconnected on the desk interface.**

![image](https://github.com/frankaemika/franka_ros/assets/133858812/3b7d0100-96b8-4a84-b430-a507250cab4e)

![image](https://github.com/frankaemika/franka_ros/assets/133858812/8b3fc6f9-0e9b-4b41-a0a4-44aa60773d7c)

**When simultaneously adjusting the Planning Group to panda_hand, there will be the following error:**

![image](https://github.com/frankaemika/franka_ros/assets/133858812/6deacbcf-8f6b-4c6d-9176-6fbdfa462c02)

**Comment by rhaschke** [comment] 2024-04-07 14:20
Duplicate of https://github.com/ros-planning/panda_moveit_config/issues/141

**Closed by rhaschke** 2024-04-07 14:20 UTC
