### ISSUE TITLE
move_group crashes using MoveGroupInterface

### ISSUE THREAD

**Issue by wumin199** [ros-planning/moveit#1485] opened 2019-05-28 01:56 UTC
### Description

When I conduct a test with MoveGroupInterface, I notice that when I was doing like:

```C++
Moveit: : planning_interface: : MoveGroupInterface group ("my_group");
......
group.plan (my_plan);
group.execute (my_plan);
```

Before the end of the execution , I quit the process using:

`group.stop ()`

After a similar procedure is tested multiple times, the move_group node collapses

### Your environment
* ROS Distro: Kinect
* OS Version: Ubuntu 16.04
* Binary build
* release version: 0.9.15-Alpha

### Steps to reproduce

first step: `roslaunch er7_moveit_config demo.launch`

second step: run my test case

This is my test case codes:

```C++
#include <ros/ros.h>
#include <moveit/move_group_interface/move_group_interface.h>
#include <iostream>

moveit::planning_interface::MoveGroupInterface::Plan path_plan(std::vector<double> current_joint_values);

int main(int argc, char **argv)
{

  ros::init(argc, argv, "moveit_async_execute");

  ros::AsyncSpinner spinner(1);
  spinner.start();

  moveit::planning_interface::MoveGroupInterface group("arm_er7");

  //async execute
  int num = 0;
  while (true)
  {
    ROS_INFO_STREAM("group.asyncExecute() cycle number : "<<(++num));
    moveit::planning_interface::MoveGroupInterface::Plan my_plan;
    my_plan = path_plan(group.getCurrentJointValues());
    moveit::planning_interface::MoveItErrorCode error = group.asyncExecute(my_plan);

    double t;

    if ((num % 3) == 0)
    {
      t = 3.0;
    }
    else if ((num % 3) == 1)
    {
      t = 5.0;
    }
    else
    {
      t = 7.0;
    }

    ROS_INFO_STREAM("asyncExecute result is " << error);
    ROS_INFO_STREAM("sleep time is : "<<t);
    ros::Duration(t).sleep();
    group.stop();
    ROS_INFO_STREAM("group.stoppep..");
    ros::Duration(2.0).sleep();

  }

  ROS_INFO("async execute test done");

  //ros::waitForShutdown();

}

moveit::planning_interface::MoveGroupInterface::Plan path_plan(std::vector<double> current_joint_values)
{
  moveit::planning_interface::MoveGroupInterface::Plan my_plan;

  my_plan.trajectory_.joint_trajectory.joint_names.push_back("joint_1");
  my_plan.trajectory_.joint_trajectory.joint_names.push_back("joint_2");
  my_plan.trajectory_.joint_trajectory.joint_names.push_back("joint_3");
  my_plan.trajectory_.joint_trajectory.joint_names.push_back("joint_4");
  my_plan.trajectory_.joint_trajectory.joint_names.push_back("joint_5");
  my_plan.trajectory_.joint_trajectory.joint_names.push_back("joint_6");
  my_plan.trajectory_.joint_trajectory.header.seq = 0;
  my_plan.trajectory_.joint_trajectory.header.frame_id = "/base_link";

  my_plan.trajectory_.joint_trajectory.points.resize(10);
  for(int i = 0; i < 10; i++)
  {
    my_plan.trajectory_.joint_trajectory.points[i].velocities.resize(6);
    my_plan.trajectory_.joint_trajectory.points[i].accelerations.resize(6);
    my_plan.trajectory_.joint_trajectory.points[i].positions = current_joint_values;
  }

  ros::Duration dur(0), dur1(0.544*5), dur2(0.7699*5), dur3(0.9458*5),dur4(1.0958*5),
      dur5(1.2289*5),dur6(1.3774*5), dur7(1.5516*5),dur8(1.7772*5), dur9(2.32592*5);

  my_plan.trajectory_.joint_trajectory.points[0].time_from_start = dur;
  my_plan.trajectory_.joint_trajectory.points[1].time_from_start = dur1;
  my_plan.trajectory_.joint_trajectory.points[2].time_from_start = dur2;
  my_plan.trajectory_.joint_trajectory.points[3].time_from_start = dur3;
  my_plan.trajectory_.joint_trajectory.points[4].time_from_start = dur4;
  my_plan.trajectory_.joint_trajectory.points[5].time_from_start = dur5;
  my_plan.trajectory_.joint_trajectory.points[6].time_from_start = dur6;
  my_plan.trajectory_.joint_trajectory.points[7].time_from_start = dur7;
  my_plan.trajectory_.joint_trajectory.points[8].time_from_start = dur8;


  my_plan.trajectory_.joint_trajectory.points[0].positions[4] = current_joint_values[4];
  my_plan.trajectory_.joint_trajectory.points[1].positions[4] = -0.147344;
  my_plan.trajectory_.joint_trajectory.points[2].positions[4] = -0.294688;
  my_plan.trajectory_.joint_trajectory.points[3].positions[4] = -0.442033;
  my_plan.trajectory_.joint_trajectory.points[4].positions[4] = -0.589377;
  my_plan.trajectory_.joint_trajectory.points[5].positions[4] = -0.736721;
  my_plan.trajectory_.joint_trajectory.points[6].positions[4] = -0.884065;
  my_plan.trajectory_.joint_trajectory.points[7].positions[4] = -1.03141;
  my_plan.trajectory_.joint_trajectory.points[8].positions[4] = -1.17875;
  my_plan.trajectory_.joint_trajectory.points[9].positions[4] =  -1.3261;

  return my_plan;
}
```

### Expected behaviour

everything should be ok, no move_group node crashes.

### Actual behaviour

move_group node crashes.

sometimes it occurs:

```
[move_group-4] process has died [pid 6908, exit code -11, cmd /opt/ros/kinetic/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/keba/.ros/log/f719b67a-8043-11e9-b504-6c0b84aba36d/move_group-4.log].
        log file: /home/keba/.ros/log/f719b67a-8043-11e9-b504-6c0b84aba36d/move_group-4*.log
```

sometimes it occurs:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
          what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
        [move_group-4] process has died [pid 18285, exit code -6, cmd /opt/ros/kinetic/lib/moveit_ros_move_group/move_group --debug __name:=move_group __log:=/home/keba/.ros/log/cd364464-7dfe-11e9-9603-6c0b84aba36d/move_group-4.log].
        log file: /home/keba/.ros/log/cd364464-7dfe-11e9-9603-6c0b84aba36d/move_group-4*.log
```

sometimes move_group node doesn't crash, but group.execute(my_plan) doesn't work, it only received event 'stop':

          [ INFO] [1558948143.946488223]: Execution request received
          [ INFO] [1558948144.046610977]: Fake execution of trajectory
          [ INFO] [1558948146.946610868]: Received event 'stop'
          [ INFO] [1558948146.946901921]: Fake trajectory execution cancelled
          [ INFO] [1558948146.946974983]: Stopped trajectory execution.
          [ INFO] [1558948146.947070564]: Completed trajectory execution with status PREEMPTED ...
          [ INFO] [1558948154.047583302]: Received event 'stop'
          [ INFO] [1558948163.146348745]: Received event 'stop'
          [ INFO] [1558948168.246359229]: Received event 'stop'
          [ INFO] [1558948175.346355164]: Received event 'stop'
          [ INFO] [1558948184.447082443]: Received event 'stop'
          [ INFO] [1558948189.546807406]: Received event 'stop'
          [ INFO] [1558948196.647628777]: Received event 'stop'

### Backtrace or Console output

see above

**Comment by BryceStevenWilley** [comment] 2019-05-28 02:54
Closing as a duplicate of #1481, which has more information. Check there for updates.

**Closed by BryceStevenWilley** 2019-05-28 02:54 UTC
