### ISSUE TITLE
Spacenav Error while using  moveit servo tutorial

### ISSUE THREAD

**Issue by Akumar201** [ros-planning/moveit#3331] opened 2023-02-02 16:13 UTC
## Background

I am following the (moveit servoing tutorial)[https://ros-planning.github.io/moveit_tutorials/doc/realtime_servo/realtime_servo_tutorial.html], however I am getting the following error related to spacenavd

```
[ERROR] [1669672889.199512421]: Could not open the space navigator device. Did you remember to run spacenavd (as root)?
[spacenav_node_abc_ThinkPad_P17_Gen_2i_29034_5978491666214438105-1] process has died [pid 29049, exit code 1, cmd /home/abc/ws_moveit/devel/lib/spacenav_node/spacenav_node __name:=spacenav_node_abc_ThinkPad_P17_Gen_2i_29034_5978491666214438105 __log:=/home/abc/.ros/log/7bcc805e-6f61-11ed-8cc6-fb1b3c97baa8/spacenav_node_abc_ThinkPad_P17_Gen_2i_29034_5978491666214438105-1.log].
log file: /home/abc/.ros/log/7bcc805e-6f61-11ed-8cc6-fb1b3c97baa8/spacenav_node_abc_ThinkPad_P17_Gen_2i_29034_5978491666214438105-1*.log

```
## Instructions
I did git clone [UR Repo](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver). 
Run the following command 

1. roslaunch ur5_bringup.launch
2. roslaunch moveit_planning_execution.launch sim:=true
3. roslaunch move_group.launch

However, after the roslaunch move_group.launch I am getting the above error.
I tried to fix the the code using the following site http://wiki.ros.org/spacenav_node/Troubleshooting

I am using Ubuntu 20.04 and ROS Noetic

**Comment by rhaschke** [comment] 2023-02-03 09:41
Duplicate of https://github.com/ros-planning/moveit_tutorials/issues/754. Closing here.

**Closed by rhaschke** 2023-02-03 09:41 UTC
Labels: bug
