### ISSUE TITLE
fr3_moveit_config

### ISSUE THREAD

**Issue by 888xc888** [ros-planning/moveit#3509] opened 2023-10-10 06:19 UTC
I'm using fr3, how can I modify panda_moveit_config to connect the moveit to the real robot arm? thank you!
I'm a newbie and don't understand many of the concepts, can you suggest a more detailed modification?

**Comment by rhaschke** [comment] 2023-10-10 08:17
This is a duplicate of https://github.com/ros-planning/panda_moveit_config/issues/140

**Closed by rhaschke** 2023-10-10 08:17 UTC
Labels: enhancement
