### ISSUE TITLE
ROS-Moveit ERROR：Group 'arm' is not a chain

### ISSUE THREAD

**Issue by fekix9** [ros-planning/moveit#2599] opened 2021-04-12 15:38 UTC
ROS:neotic
Moveit：1.1.0-1focal.20210304.173046

When I run the demo, the model in rviz cannot be dragged and planned.

<pre>PARAMETERS
 * /joint_state_publisher/source_list: [&apos;move_group/fake...
 * /move_group/allow_trajectory_execution: True
 * /move_group/arm/default_planner_config: None
 * /move_group/arm/longest_valid_segment_fraction: 0.005
 * /move_group/arm/planner_configs: [&apos;AnytimePathShor...
 * /move_group/arm/projection_evaluator: joints(shoulder_p...
 * /move_group/capabilities: 
 * /move_group/controller_list: [{&apos;name&apos;: &apos;fake_a...
 * /move_group/disable_capabilities: 
 * /move_group/gripper/default_planner_config: None
 * /move_group/gripper/longest_valid_segment_fraction: 0.005
 * /move_group/gripper/planner_configs: [&apos;AnytimePathShor...
 * /move_group/gripper/projection_evaluator: joints(finger_joi...
 * /move_group/initial: [{&apos;group&apos;: &apos;arm&apos;,...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_fake_contr...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_resolution: 0.025
 * /move_group/planner_configs/AnytimePathShortening/hybridize: True
 * /move_group/planner_configs/AnytimePathShortening/max_hybrid_paths: 24
 * /move_group/planner_configs/AnytimePathShortening/num_planners: 4
 * /move_group/planner_configs/AnytimePathShortening/planners: 
 * /move_group/planner_configs/AnytimePathShortening/shortcut: True
 * /move_group/planner_configs/AnytimePathShortening/type: geometric::Anytim...
 * /move_group/planner_configs/BFMT/balanced: 0
 * /move_group/planner_configs/BFMT/cache_cc: 1
 * /move_group/planner_configs/BFMT/extended_fmt: 1
 * /move_group/planner_configs/BFMT/heuristics: 1
 * /move_group/planner_configs/BFMT/nearest_k: 1
 * /move_group/planner_configs/BFMT/num_samples: 1000
 * /move_group/planner_configs/BFMT/optimality: 1
 * /move_group/planner_configs/BFMT/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMT/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECE/range: 0.0
 * /move_group/planner_configs/BKPIECE/type: geometric::BKPIECE
 * /move_group/planner_configs/BiEST/range: 0.0
 * /move_group/planner_configs/BiEST/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRT/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRT/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRT/init_temperature: 100
 * /move_group/planner_configs/BiTRRT/range: 0.0
 * /move_group/planner_configs/BiTRRT/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRT/type: geometric::BiTRRT
 * /move_group/planner_configs/EST/goal_bias: 0.05
 * /move_group/planner_configs/EST/range: 0.0
 * /move_group/planner_configs/EST/type: geometric::EST
 * /move_group/planner_configs/FMT/cache_cc: 1
 * /move_group/planner_configs/FMT/extended_fmt: 1
 * /move_group/planner_configs/FMT/heuristics: 0
 * /move_group/planner_configs/FMT/nearest_k: 1
 * /move_group/planner_configs/FMT/num_samples: 1000
 * /move_group/planner_configs/FMT/radius_multiplier: 1.1
 * /move_group/planner_configs/FMT/type: geometric::FMT
 * /move_group/planner_configs/KPIECE/border_fraction: 0.9
 * /move_group/planner_configs/KPIECE/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECE/goal_bias: 0.05
 * /move_group/planner_configs/KPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECE/range: 0.0
 * /move_group/planner_configs/KPIECE/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECE/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECE/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECE/range: 0.0
 * /move_group/planner_configs/LBKPIECE/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRT/epsilon: 0.4
 * /move_group/planner_configs/LBTRRT/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRT/range: 0.0
 * /move_group/planner_configs/LBTRRT/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRM/range: 0.0
 * /move_group/planner_configs/LazyPRM/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstar/type: geometric::LazyPR...
 * /move_group/planner_configs/PDST/type: geometric::PDST
 * /move_group/planner_configs/PRM/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRM/type: geometric::PRM
 * /move_group/planner_configs/PRMstar/type: geometric::PRMstar
 * /move_group/planner_configs/ProjEST/goal_bias: 0.05
 * /move_group/planner_configs/ProjEST/range: 0.0
 * /move_group/planner_configs/ProjEST/type: geometric::ProjEST
 * /move_group/planner_configs/RRT/goal_bias: 0.05
 * /move_group/planner_configs/RRT/range: 0.0
 * /move_group/planner_configs/RRT/type: geometric::RRT
 * /move_group/planner_configs/RRTConnect/range: 0.0
 * /move_group/planner_configs/RRTConnect/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTstar/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstar/goal_bias: 0.05
 * /move_group/planner_configs/RRTstar/range: 0.0
 * /move_group/planner_configs/RRTstar/type: geometric::RRTstar
 * /move_group/planner_configs/SBL/range: 0.0
 * /move_group/planner_configs/SBL/type: geometric::SBL
 * /move_group/planner_configs/SPARS/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARS/max_failures: 1000
 * /move_group/planner_configs/SPARS/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARS/stretch_factor: 3.0
 * /move_group/planner_configs/SPARS/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwo/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwo/max_failures: 5000
 * /move_group/planner_configs/SPARStwo/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwo/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwo/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDE/degree: 16
 * /move_group/planner_configs/STRIDE/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDE/goal_bias: 0.05
 * /move_group/planner_configs/STRIDE/max_degree: 18
 * /move_group/planner_configs/STRIDE/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDE/min_degree: 12
 * /move_group/planner_configs/STRIDE/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDE/range: 0.0
 * /move_group/planner_configs/STRIDE/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDE/use_projected_distance: 0
 * /move_group/planner_configs/TRRT/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRT/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRT/goal_bias: 0.05
 * /move_group/planner_configs/TRRT/init_temperature: 10e-6
 * /move_group/planner_configs/TRRT/k_constant: 0.0
 * /move_group/planner_configs/TRRT/max_states_failed: 10
 * /move_group/planner_configs/TRRT/min_temperature: 10e-10
 * /move_group/planner_configs/TRRT/range: 0.0
 * /move_group/planner_configs/TRRT/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRT/type: geometric::TRRT
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{}]
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/allowed_start_tolerance: 0.01
 * /robot_description: &lt;?xml version=&quot;1....
 * /robot_description_kinematics/arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/arm/kinematics_solver_timeout: 0.05
 * /robot_description_planning/default_acceleration_scaling_factor: 0.1
 * /robot_description_planning/default_velocity_scaling_factor: 0.1
 * /robot_description_planning/joint_limits/elbow_pitch_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/elbow_pitch_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/elbow_pitch_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/elbow_pitch_joint/max_velocity: 1
 * /robot_description_planning/joint_limits/finger_joint1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/finger_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/finger_joint1/max_acceleration: 0
 * /robot_description_planning/joint_limits/finger_joint1/max_velocity: 1
 * /robot_description_planning/joint_limits/finger_joint2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/finger_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/finger_joint2/max_acceleration: 0
 * /robot_description_planning/joint_limits/finger_joint2/max_velocity: 1
 * /robot_description_planning/joint_limits/gripper_roll_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/gripper_roll_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/gripper_roll_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/gripper_roll_joint/max_velocity: 1
 * /robot_description_planning/joint_limits/shoulder_pan_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/shoulder_pan_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/shoulder_pan_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/shoulder_pan_joint/max_velocity: 1
 * /robot_description_planning/joint_limits/shoulder_pitch_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/shoulder_pitch_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/shoulder_pitch_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/shoulder_pitch_joint/max_velocity: 1
 * /robot_description_planning/joint_limits/wrist_pitch_joint/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/wrist_pitch_joint/has_velocity_limits: True
 * /robot_description_planning/joint_limits/wrist_pitch_joint/max_acceleration: 0
 * /robot_description_planning/joint_limits/wrist_pitch_joint/max_velocity: 1
 * /robot_description_semantic: &lt;?xml version=&quot;1....
 * /rosdistro: noetic
 * /rosversion: 1.15.9

NODES
  /
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz_fekix_Lenovo_XiaoXin_RUI7000_31814_8357963318253057231 (rviz/rviz)

auto-starting new master
<b>process[master]: started with pid [31826]</b>
<b>ROS_MASTER_URI=http://localhost:11311</b>

<b>setting /run_id to c05be320-9ba2-11eb-a308-013b15df5e16</b>
<b>process[rosout-1]: started with pid [31836]</b>
started core service [/rosout]
<b>process[joint_state_publisher-2]: started with pid [31843]</b>
<b>process[robot_state_publisher-3]: started with pid [31844]</b>
<b>process[move_group-4]: started with pid [31845]</b>
<b>process[rviz_fekix_Lenovo_XiaoXin_RUI7000_31814_8357963318253057231-5]: started with pid [31846]</b>
[ INFO] [1618240888.816686974]: Loading robot model &apos;myarm1&apos;...
[ INFO] [1618240888.824370797]: No root/virtual joint specified in SRDF. Assuming fixed joint
<font color="#C4A000">[ WARN] [1618240888.824636350]: Link gripper_finger_link1 has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#C4A000">[ WARN] [1618240888.824723394]: Link gripper_finger_link2 has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#C4A000">[ WARN] [1618240888.824790706]: Link grasping_frame has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
[ INFO] [1618240888.881546682]: Publishing maintained planning scene on &apos;monitored_planning_scene&apos;
[ INFO] [1618240888.883857251]: MoveGroup debug mode is ON
<font color="#34E2E2">Starting planning scene monitors...</font>
[ INFO] [1618240888.883911854]: Starting planning scene monitor
[ INFO] [1618240888.885780610]: Listening to &apos;/planning_scene&apos;
[ INFO] [1618240888.885830949]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[ INFO] [1618240888.887698020]: Listening to &apos;/collision_object&apos;
[ INFO] [1618240888.889537894]: Listening to &apos;/planning_scene_world&apos; for planning scene world geometry
<font color="#CC0000">[ERROR] [1618240888.890270879]: No sensor plugin specified for octomap updater 0; ignoring.</font>
[ INFO] [1618240888.895643656]: Listening to &apos;/attached_collision_object&apos; for attached collision objects
<font color="#34E2E2">Planning scene monitors started.</font>
<font color="#CC0000">[ERROR] [1618240888.930406522]: Could not find the planner configuration &apos;None&apos; on the param server</font>
<font color="#CC0000">[ERROR] [1618240888.940747956]: Could not find the planner configuration &apos;None&apos; on the param server</font>
[ INFO] [1618240888.957489922]: Using planning interface &apos;OMPL&apos;
[ INFO] [1618240888.960883586]: Param &apos;default_workspace_bounds&apos; was not set. Using default value: 10
[ INFO] [1618240888.961346987]: Param &apos;start_state_max_bounds_error&apos; was set to 0.1
[ INFO] [1618240888.961725374]: Param &apos;start_state_max_dt&apos; was not set. Using default value: 0.5
[ INFO] [1618240888.962105874]: Param &apos;start_state_max_dt&apos; was not set. Using default value: 0.5
[ INFO] [1618240888.962459304]: Param &apos;jiggle_fraction&apos; was set to 0.05
[ INFO] [1618240888.962806082]: Param &apos;max_sampling_attempts&apos; was not set. Using default value: 100
[ INFO] [1618240888.962872642]: Using planning request adapter &apos;Add Time Parameterization&apos;
[ INFO] [1618240888.962909188]: Using planning request adapter &apos;Resolve constraint frames to robot links&apos;
[ INFO] [1618240888.962938354]: Using planning request adapter &apos;Fix Workspace Bounds&apos;
[ INFO] [1618240888.962965087]: Using planning request adapter &apos;Fix Start State Bounds&apos;
[ INFO] [1618240888.962992786]: Using planning request adapter &apos;Fix Start State In Collision&apos;
[ INFO] [1618240888.963020166]: Using planning request adapter &apos;Fix Start State Path Constraints&apos;
[ INFO] [1618240888.971820946]: Loading robot model &apos;myarm1&apos;...
[ INFO] [1618240888.971895052]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1618240888.973356418]: rviz version 1.14.5
[ INFO] [1618240888.973404038]: compiled against Qt version 5.12.8
[ INFO] [1618240888.973414956]: compiled against OGRE version 1.9.0 (Ghadamon)
<font color="#C4A000">[ WARN] [1618240888.974823807]: Link gripper_finger_link1 has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#C4A000">[ WARN] [1618240888.974994018]: Link gripper_finger_link2 has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#C4A000">[ WARN] [1618240888.975086630]: Link grasping_frame has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
[ INFO] [1618240888.988488255]: Forcing OpenGl version 0.
[ INFO] [1618240889.004583381]: Set joints of group &apos;arm&apos; to pose &apos;home&apos;.
[ INFO] [1618240889.004890541]: Fake controller &apos;fake_arm_controller&apos; with joints [ shoulder_pan_joint shoulder_pitch_joint elbow_pitch_joint wrist_pitch_joint gripper_roll_joint ]
[ INFO] [1618240889.006047685]: Fake controller &apos;fake_gripper_controller&apos; with joints [ finger_joint1 finger_joint2 ]
[ INFO] [1618240889.007065806]: Returned 2 controllers in list
[ INFO] [1618240889.017209185]: Trajectory execution is managing controllers
<font color="#34E2E2">Loading &apos;move_group/ApplyPlanningSceneService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/ClearOctomapService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupCartesianPathService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupExecuteTrajectoryAction&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupGetPlanningSceneService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupKinematicsService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupMoveAction&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupPickPlaceAction&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupPlanService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupQueryPlannersService&apos;...</font>
<font color="#34E2E2">Loading &apos;move_group/MoveGroupStateValidationService&apos;...</font>
[ INFO] [1618240889.079284015]: 

********************************************************
* MoveGroup using: 
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1618240889.079379197]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1618240889.079411773]: MoveGroup context initialization complete

<font color="#8AE234">You can start planning now!</font>

[ INFO] [1618240889.215375193]: Stereo is NOT SUPPORTED
[ INFO] [1618240889.215442760]: OpenGL device: Mesa Intel(R) HD Graphics 630 (KBL GT2)
[ INFO] [1618240889.215467995]: OpenGl version: 4.6 (GLSL 4.6) limited to GLSL 1.4 on Mesa system.
[ INFO] [1618240892.538014245]: Loading robot model &apos;myarm1&apos;...
[ INFO] [1618240892.538069791]: No root/virtual joint specified in SRDF. Assuming fixed joint
<font color="#C4A000">[ WARN] [1618240892.538354618]: Link gripper_finger_link1 has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#C4A000">[ WARN] [1618240892.538385975]: Link gripper_finger_link2 has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#C4A000">[ WARN] [1618240892.538402547]: Link grasping_frame has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.</font>
<font color="#CC0000">[ERROR] [1618240892.574731094]: Group &apos;arm&apos; is not a chain</font>
<font color="#CC0000">[ERROR] [1618240892.575428985]: Kinematics solver of type &apos;kdl_kinematics_plugin/KDLKinematicsPlugin&apos; could not be initialized for group &apos;arm&apos;</font>
<font color="#CC0000">[ERROR] [1618240892.575765806]: Kinematics solver could not be instantiated for joint group arm.</font>
[ INFO] [1618240892.616883299]: Starting planning scene monitor
[ INFO] [1618240892.619470256]: Listening to &apos;/move_group/monitored_planning_scene&apos;
[ INFO] [1618240892.641831406]: No active joints or end effectors found for group &apos;arm&apos;. Make sure that kinematics.yaml is loaded in this node&apos;s namespace.
[ INFO] [1618240892.643472983]: No active joints or end effectors found for group &apos;arm&apos;. Make sure that kinematics.yaml is loaded in this node&apos;s namespace.
[ INFO] [1618240892.648170398]: Constructing new MoveGroup connection for group &apos;arm&apos; in namespace &apos;&apos;
<font color="#CC0000">[ERROR] [1618240892.951707093]: Client [/move_group] wants topic /move_group/goal to have datatype/md5sum [moveit_msgs/MoveGroupActionGoal/689f0d7213d5960a2a9e9b117a0fdb73], but our version has [moveit_msgs/MoveGroupActionGoal/6514728724a6f4ce3f2f5a26db255bc9]. Dropping connection.</font>
<font color="#CC0000">[ERROR] [1618240922.662611634]: Unable to connect to move_group action server &apos;move_group&apos; within allotted time (30s)</font>
[ INFO] [1618240922.662944787]: Constructing new MoveGroup connection for group &apos;arm&apos; in namespace &apos;&apos;
<font color="#CC0000">[ERROR] [1618240922.919773550]: Client [/move_group] wants topic /move_group/goal to have datatype/md5sum [moveit_msgs/MoveGroupActionGoal/689f0d7213d5960a2a9e9b117a0fdb73], but our version has [moveit_msgs/MoveGroupActionGoal/6514728724a6f4ce3f2f5a26db255bc9]. Dropping connection.</font>
<font color="#CC0000">[ERROR] [1618240952.678639832]: Unable to connect to move_group action server &apos;move_group&apos; within allotted time (30s)</font>
</pre>

Can someone help me? What caused this? Is it a version issue?

**Comment by fekix9** [comment] 2021-04-12 15:48
My xacro and srdf files are [here](https://github.com/fekix9/moveit_myarm_version1.0)  . I used moveit_setup_assistant to generate   
 demo.launch.

**Comment by felixvd** [comment] 2021-04-13 06:54
Duplicate of [this ROS Answers question](https://answers.ros.org/question/375513/error-group-arm-is-not-a-chain/)

**Comment by fekix9** [comment] 2021-04-13 07:09
The problem is not solved

**Comment by v4hn** [comment] 2021-04-13 07:33
Nobody claimed that, but let's keep the discussion in one place. Sorry for not responding there. You didn't address @felixvd's questions there yet.

> Did you try removing the inertia from the base link and fixing the other errors? It seems like your versions don't match or you are building parts of moveit from source but not others. I don't see anything obviously wrong in the SRDF/URDF, but a picture would help. I might also try removing the gripper chain and end effector from the SRDF for debugging.

As long as you use inconsistent versions of MoveIt in the same workspace(s) - as indicated by the topic type discrepancy - that is the most likely source of your problem. I don't see anything obviously wrong with the description files.

**Closed by v4hn** 2021-04-13 07:33 UTC

**Comment by fekix9** [comment] 2021-04-13 09:15
May be you are right.But I don't know how to fix it.
